### ISSUE TITLE
DEPRECATION: An addon is trying to access project.nodeModulesPath.

### ISSUE THREAD

**Issue by rinoldsimon** [kimroen/ember-cli-document-title#69] opened 2018-01-23 13:29 UTC
The following deprecation is thrown on a new Ember `2.18.0` Version when starting the server. It seems some package needs to be updated.

This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/Users/username/emberApp/node_modules/ember-cli-document-title/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)

**Comment by JHKennedy4** [comment] 2018-02-01 19:09
Just need to upgrade the version checker: https://github.com/ember-cli/ember-cli-version-checker/issues/48

**Comment by dgavey** [comment] 2018-02-02 21:23
I can make a PR for this if one is needed.

**Comment by backspace** [comment] 2018-02-05 16:44
I’d appreciate that, @dgavey, or I could do it too, but I’m not sure if @kimroen is around to merge one!

**Comment by kimroen** [comment] 2018-02-05 17:59
There are a lot of updates on the master branch - would anyone mind confirming that this deprecation warning isn't there on master?

**Comment by backspace** [comment] 2018-02-05 20:31
I’m generally confused about how to figure out the source of these deprecations warnings when npm has flattened `node_modules`, but in [this job](https://travis-ci.org/backspace/document-title-test/builds/337724847) I added the `master` branch and the warning is absent, so perhaps it’s indeed fixed!

(I also tried it [on `travis-web`](https://travis-ci.org/travis-ci/travis-web/jobs/337670517) and the warning shows there twice, which is why I decided to try it on a new Ember project instead.)

**Comment by backspace** [comment] 2018-02-06 14:28
I think this can be called a TOTAL SUCCESS

![image](https://user-images.githubusercontent.com/43280/35864538-adec1c60-0b17-11e8-8e05-95964e60039b.png)

**Comment by kariavka** [comment] 2018-02-06 18:16
+1

**Comment by josemarluedke** [comment] 2018-02-13 19:27
I can confirm that master fixes this deprecation.

**Comment by The-Don-Himself** [comment] 2018-02-14 04:23
For anyone wondering the root cause: https://discuss.emberjs.com/t/deprecation-warning-for-addons-future-big-problems/14204/3

To quote @broerse

"All modules that have this error user ember-cli-babel 5 and just need to upgrade to addon to en newer ember-cli that uses ember-cli-babel 6..."

Meanwhile, this PR is what fixes it in the master branch: https://github.com/kimroen/ember-cli-document-title/pull/67

**Comment by jrjohnson** [comment] 2018-02-21 07:20
@kimroen I can also confirm that this is resolved on `master` just need to cut a release.

**Comment by Alonski** [comment] 2018-03-13 20:00
Ping to please get a new release

**Comment by kimroen** [comment] 2018-04-02 14:17
Hi everyone!

There's now a release that contains a fix for this issue - version `0.4.0`: https://github.com/kimroen/ember-cli-document-title/releases/tag/v0.4.0

Thank you for your patience, and sorry that I didn't get around to it sooner ❤️

**Closed by kimroen** 2018-04-02 14:17 UTC
